export declare const WINDOW: Window & typeof globalThis;
export declare const LOCATION: Location;
export declare const HISTORY: History;
export declare const UNDEFINED: undefined;
export declare const NULL: null;
export declare const TRUE = true;
export declare const FALSE = false;
export declare const RAW_NULL = "null";
export declare const RAW_TRUE = "true";
export declare const RAW_FALSE = "false";
export declare const PREFIX_PARAM = ":";
export declare const SEPARATOR_PATH = "/";
export declare const SEPARATOR_SEARCH = "?";
export declare const SEPARATOR_QUERY = "&";
export declare const SEPARATOR_PAIR = "=";
export declare const FLAG_ARRAY = "[]";
export declare const MODE_HISTORY = "history";
export declare const ROUTER_HOOK_BEFORE_ENTER = "beforeEnter";
export declare const ROUTER_HOOK_AFTER_ENTER = "afterEnter";
export declare const ROUTER_HOOK_BEFORE_UPDATE = "beforeUpdate";
export declare const ROUTER_HOOK_AFTER_UPDATE = "afterUpdate";
export declare const ROUTER_HOOK_BEFORE_LEAVE = "beforeLeave";
export declare const ROUTER_HOOK_AFTER_LEAVE = "afterLeave";
export declare const ROUTER_HOOK_BEFORE_LOAD = "beforeLoad";
export declare const ROUTER_HOOK_AFTER_LOAD = "afterLoad";
export declare const COMPONENT_HOOK_BEFORE_ENTER = "beforeRouteEnter";
export declare const COMPONENT_HOOK_AFTER_ENTER = "afterRouteEnter";
export declare const COMPONENT_HOOK_BEFORE_UPDATE = "beforeRouteUpdate";
export declare const COMPONENT_HOOK_AFTER_UPDATE = "afterRouteUpdate";
export declare const COMPONENT_HOOK_BEFORE_LEAVE = "beforeRouteLeave";
export declare const COMPONENT_HOOK_AFTER_LEAVE = "afterRouteLeave";
